#!/usr/bin/env bash

# cd into this directory
mypath=`realpath $0`
cd `dirname $mypath`
pwd
while true
do
    python3 bot.py # run the bot
    # if we crash, check internet connection before trying again
    # wait 10 seconds if there is internet connection else 10 minutes
    ping -q -w1 -c1 google.com &>/dev/null && sleep 10 || sleep 600
done

